services:
  meshsense:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshsense
    environment:
      - ADDRESS=192.168.178.89  # Address of Meshtastic Node
    #      - ACCESS_KEY=myAccessKey  # Optional access key      - PORT=5920  # Optional port
    restart: unless-stopped
    ports:
      - "5920:5920"  # Web interface port
